// Package git implements Git-based deployments: a site pulls its content/app
// from a Git repository, builds it as the site's own unprivileged Linux user,
// and activates the result with an atomic, reversible release swap. It reuses the
// Sites module's per-site isolation (no new privilege) and drives the privileged
// broker capabilities git.deploy / git.rollback. See docs/11-git-deployments.md.
package git

import (
	"context"
	"database/sql"
	"net/url"
	"regexp"
	"strings"

	"github.com/thisisnkp/heropanel/pkg/errx"
)

// keepReleases is how many past releases to retain per site (the live one is
// never pruned). Passed through to the broker's git.deploy.
const keepReleases = 5

// Trigger records what initiated a deployment.
const (
	TriggerManual   = "manual"
	TriggerWebhook  = "webhook"
	TriggerRollback = "rollback"
)

// Authentication kinds for a source.
const (
	// AuthNone is a public repository over https.
	AuthNone = "none"
	// AuthToken is HTTPS with a personal access token (GitHub PAT, GitLab token,
	// Bitbucket app password) presented as basic-auth credentials.
	AuthToken = "token"
	// AuthSSHKey is SSH with a deploy key generated by the panel. The operator
	// registers the public half on the repository; the private half never leaves
	// the server unencrypted.
	AuthSSHKey = "ssh_key"
)

var validAuthKinds = map[string]bool{AuthNone: true, AuthToken: true, AuthSSHKey: true}

// Deployment status values.
const (
	StatusPending    = "pending"
	StatusRunning    = "running"
	StatusSuccess    = "success"
	StatusFailed     = "failed"
	StatusRolledBack = "rolled_back"
)

// Source is the API view of a site's Git source. It never carries the token or
// the private half of a deploy key — only whether one is configured.
type Source struct {
	UID          string `json:"uid"`
	RepoURL      string `json:"repo_url"`
	Branch       string `json:"branch"`
	BuildCommand string `json:"build_command"`
	WebRoot      string `json:"web_root"`
	// AuthKind is one of the Auth* constants.
	AuthKind string `json:"auth_kind"`
	// AuthUsername is the basic-auth username for AuthToken sources (not secret).
	AuthUsername string `json:"auth_username,omitempty"`
	// PublicKey is the deploy key to register on the repository (AuthSSHKey only).
	PublicKey string `json:"public_key,omitempty"`
	// HostKey pins the repo host's SSH host key(s) (ssh-keyscan / known_hosts
	// format). When set, clones use strict host-key checking so the first
	// connection is verified too; empty falls back to accept-new (TOFU). Public,
	// so it is safe to return. AuthSSHKey only.
	HostKey string `json:"host_key,omitempty"`
	// AutoComposer runs `composer install` when the release has a composer.json.
	AutoComposer bool `json:"auto_composer"`
	// WebhookURL is the push endpoint; the secret is embedded as a query param so
	// it is shown once and never returned in list responses.
	WebhookURL string `json:"webhook_url,omitempty"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

// Deployment is the API view of one deploy in a site's history.
type Deployment struct {
	UID        string `json:"uid"`
	CommitSHA  string `json:"commit_sha"`
	Status     string `json:"status"`
	Trigger    string `json:"trigger"`
	Log        string `json:"log,omitempty"`
	CreatedAt  string `json:"created_at"`
	FinishedAt string `json:"finished_at,omitempty"`
}

// SourceRecord is the persistence row for a site's Git source. CredentialEnc is
// the sealed token or private key (see pkg/secrets); it is decrypted only in the
// moment a deploy hands it to the broker.
type SourceRecord struct {
	ID            int64  `db:"id"`
	UID           string `db:"uid"`
	SiteID        int64  `db:"site_id"`
	RepoURL       string `db:"repo_url"`
	Branch        string `db:"branch"`
	BuildCommand  string `db:"build_command"`
	WebRoot       string `db:"web_root"`
	WebhookSecret string `db:"webhook_secret"`
	AuthKind      string `db:"auth_kind"`
	AuthUsername  string `db:"auth_username"`
	CredentialEnc string `db:"credential_enc"`
	PublicKey     string `db:"public_key"`
	HostKey       string `db:"host_key"`
	AutoComposer  bool   `db:"auto_composer"`
	CreatedAt     string `db:"created_at"`
	UpdatedAt     string `db:"updated_at"`
}

// DeploymentRecord is the persistence row for a deployment.
type DeploymentRecord struct {
	ID          int64          `db:"id"`
	UID         string         `db:"uid"`
	SiteID      int64          `db:"site_id"`
	SourceID    int64          `db:"source_id"`
	CommitSHA   string         `db:"commit_sha"`
	Status      string         `db:"status"`
	TriggerKind string         `db:"trigger_kind"`
	ReleaseDir  string         `db:"release_dir"`
	Log         string         `db:"log"`
	CreatedAt   string         `db:"created_at"`
	FinishedAt  sql.NullString `db:"finished_at"`
}

// Repo is the persistence contract (implemented by internal/repository).
type Repo interface {
	UpsertSource(ctx context.Context, r *SourceRecord) error
	GetSourceBySiteID(ctx context.Context, siteID int64) (*SourceRecord, error)
	InsertDeployment(ctx context.Context, r *DeploymentRecord) error
	UpdateDeployment(ctx context.Context, r *DeploymentRecord) error
	ListDeployments(ctx context.Context, siteID int64, limit int) ([]DeploymentRecord, error)
	GetDeploymentByUID(ctx context.Context, uid string) (*DeploymentRecord, error)
}

// SiteRef is the minimal site identity/paths a deploy needs.
type SiteRef struct {
	ID         int64
	UID        string
	LinuxUser  string
	HomeDir    string
	DeployMode string
}

// Sites resolves a site's identity/paths by UID (implemented by an adapter over
// the site repository — keeps the git service off the concrete store).
type Sites interface {
	Resolve(ctx context.Context, siteUID string) (*SiteRef, error)
}

// SetSourceInput is the request to configure/replace a site's Git source.
type SetSourceInput struct {
	RepoURL      string
	Branch       string
	BuildCommand string
	WebRoot      string
	// AuthKind is one of the Auth* constants; empty means AuthNone.
	AuthKind string
	// AuthUsername is the basic-auth username for AuthToken. Defaults to a
	// provider-appropriate placeholder when empty (see defaultTokenUsername).
	AuthUsername string
	// Token is the personal access token for AuthToken. Write-only: on an update
	// an empty Token keeps the stored one, so an operator can change the branch
	// without re-pasting the token.
	Token string
	// RotateKey forces a fresh deploy keypair for an AuthSSHKey source. Without
	// it, re-saving a source keeps the existing key so the operator does not have
	// to re-register it on the repository.
	RotateKey bool
	// HostKey pins the repo host's SSH host key(s) for AuthSSHKey sources (see
	// Source.HostKey). Empty leaves the stored value untouched on update, so it
	// can be set once and kept across branch changes.
	HostKey string
	// AutoComposer toggles `composer install` on deploy. nil means "unspecified":
	// keep the stored setting, or default to on for a new source. A tri-state is
	// worth the pointer here — a plain bool would silently disable Composer on
	// every API client that does not know the field yet.
	AutoComposer *bool
}

// ── validation ───────────────────────────────────────────────────────────────

var (
	// reRef: a git branch / relative subpath token. Deliberately strict so the
	// value is safe to build filesystem paths from and cannot masquerade as a
	// CLI flag. No whitespace, no shell metacharacters.
	reRef = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$`)
)

func validateSetSource(in *SetSourceInput) error {
	in.RepoURL = strings.TrimSpace(in.RepoURL)
	in.Branch = strings.TrimSpace(in.Branch)
	in.BuildCommand = strings.TrimSpace(in.BuildCommand)
	in.WebRoot = strings.Trim(strings.TrimSpace(in.WebRoot), "/")
	in.AuthKind = strings.TrimSpace(in.AuthKind)
	in.AuthUsername = strings.TrimSpace(in.AuthUsername)

	if in.AuthKind == "" {
		in.AuthKind = AuthNone
	}
	if !validAuthKinds[in.AuthKind] {
		return errx.Validation("invalid_auth_kind", "Authentication must be none, token, or ssh_key.",
			errx.Field{Field: "auth_kind", Code: "unsupported", Message: "none|token|ssh_key"})
	}
	if err := validateRepoURL(in.RepoURL, in.AuthKind); err != nil {
		return err
	}
	if err := validateAuth(in); err != nil {
		return err
	}
	if in.Branch == "" {
		in.Branch = "main"
	}
	if !reRef.MatchString(in.Branch) || strings.Contains(in.Branch, "..") {
		return errx.Validation("invalid_branch", "Branch contains invalid characters.",
			errx.Field{Field: "branch", Code: "invalid", Message: "invalid branch"})
	}
	if in.WebRoot != "" && (!reRef.MatchString(in.WebRoot) || strings.Contains(in.WebRoot, "..")) {
		return errx.Validation("invalid_web_root", "Web root must be a relative path with no '..'.",
			errx.Field{Field: "web_root", Code: "invalid", Message: "invalid web root"})
	}
	if len(in.BuildCommand) > 1000 {
		return errx.Validation("build_command_too_long", "Build command is too long (max 1000 chars).")
	}
	if strings.ContainsRune(in.BuildCommand, '\x00') {
		return errx.Validation("invalid_build_command", "Build command contains an invalid byte.")
	}
	return nil
}

// reSCPLike matches git's scp-style remote, `[user@]host:path` — the form
// GitHub/GitLab/Bitbucket hand out for SSH clones. The path may be relative
// (`git@github.com:owner/repo.git`) or absolute (`git@host:/srv/git/repo.git`,
// which is what self-hosted remotes usually look like).
//
// Deliberately strict otherwise: no whitespace, no shell metacharacters, and the
// first path character must be alphanumeric so the path cannot start climbing.
var reSCPLike = regexp.MustCompile(`^(?:[A-Za-z0-9._-]+@)?[A-Za-z0-9.-]+:/?[A-Za-z0-9][A-Za-z0-9._/~-]{0,254}$`)

// validateRepoURL checks the remote and, crucially, that it matches how the
// deploy will authenticate. A token is basic-auth over HTTPS and an ssh:// URL
// would silently ignore it; a deploy key is useless against an https:// remote.
// Rejecting the mismatch here turns a confusing "authentication failed" at clone
// time into a clear error at save time.
func validateRepoURL(raw, authKind string) error {
	invalid := func(msg string) error {
		return errx.Validation("invalid_repo_url", msg,
			errx.Field{Field: "repo_url", Code: "invalid", Message: "invalid url"})
	}
	if raw == "" || len(raw) > 512 {
		return invalid("A repository URL is required.")
	}
	// No characters that could be misread as an argv flag or split by any
	// downstream tool, whatever the scheme.
	if strings.ContainsAny(raw, " \t\r\n") || strings.HasPrefix(raw, "-") {
		return invalid("The repository URL contains invalid characters.")
	}

	if authKind == AuthSSHKey {
		if reSCPLike.MatchString(raw) && !strings.Contains(raw, "..") {
			return nil
		}
		u, err := url.Parse(raw)
		if err != nil || u.Scheme != "ssh" || u.Host == "" || u.Path == "" || strings.Contains(u.Path, "..") {
			return invalid("A deploy key needs an SSH remote, e.g. git@github.com:owner/repo.git.")
		}
		return nil
	}

	u, err := url.Parse(raw)
	if err != nil || u.Scheme != "https" || u.Host == "" || u.Path == "" {
		if authKind == AuthToken {
			return invalid("A token needs an https:// repository URL.")
		}
		return invalid("A valid https:// repository URL is required.")
	}
	// Credentials belong in the encrypted credential column, not in a URL that
	// lands in logs, argv, and the API response.
	if u.User != nil {
		return invalid("Do not put credentials in the URL — set authentication to \"token\" instead.")
	}
	return nil
}

// validateAuth checks the credential fields against the chosen auth kind.
func validateAuth(in *SetSourceInput) error {
	switch in.AuthKind {
	case AuthNone:
		// Clear anything the caller sent along; a public repo stores no secret.
		in.AuthUsername, in.Token = "", ""
	case AuthToken:
		if len(in.Token) > 4096 || strings.ContainsAny(in.Token, " \t\r\n\x00") {
			return errx.Validation("invalid_token", "The access token contains invalid characters.",
				errx.Field{Field: "token", Code: "invalid", Message: "invalid token"})
		}
		if in.AuthUsername == "" {
			in.AuthUsername = defaultTokenUsername(in.RepoURL)
		}
		if len(in.AuthUsername) > 190 || strings.ContainsAny(in.AuthUsername, " \t\r\n\x00:/@") {
			return errx.Validation("invalid_auth_username", "The username contains invalid characters.",
				errx.Field{Field: "auth_username", Code: "invalid", Message: "invalid username"})
		}
	case AuthSSHKey:
		// The panel generates the keypair; a caller-supplied private key is
		// refused so no unvetted key material enters the store.
		in.AuthUsername, in.Token = "", ""
	}
	// The pinned host key is public but ends up in a known_hosts file the broker
	// feeds to ssh. Bound the size and forbid a NUL so it cannot smuggle anything
	// past ssh's line parser; newlines are allowed (multiple known_hosts lines).
	in.HostKey = strings.TrimSpace(in.HostKey)
	if len(in.HostKey) > 4096 || strings.ContainsRune(in.HostKey, '\x00') {
		return errx.Validation("invalid_host_key", "The host key is malformed.",
			errx.Field{Field: "host_key", Code: "invalid", Message: "invalid host key"})
	}
	return nil
}

// defaultTokenUsername picks the basic-auth username each host expects when the
// password is a personal access token. Getting this wrong is the single most
// common cause of a "works in my terminal, fails in the panel" token clone.
func defaultTokenUsername(repoURL string) string {
	u, err := url.Parse(repoURL)
	if err != nil {
		return "git"
	}
	switch strings.ToLower(u.Hostname()) {
	case "github.com":
		return "x-access-token"
	case "gitlab.com":
		return "oauth2"
	case "bitbucket.org":
		return "x-token-auth"
	default:
		return "git"
	}
}
