/**
 * The icon registry — generated by scripts/gen-icons.mjs, do not edit by hand.
 *
 * unplugin-icons resolves each import at build time and inlines the SVG, so a
 * screen ships only the glyphs it renders. That resolution is static, which is
 * why this file exists: the navigation model stores icon *names* as strings, and
 * a string cannot be an import. Mapping them here keeps the dynamic lookup
 * without falling back to Iconify's runtime API, which would fetch every glyph
 * over the network on first paint.
 *
 * Every name resolves to the `-outline` variant of the glyph. The design sets
 * `FILL 0` on Material Symbols, so its icons are outlined; Iconify's bare name
 * (`material-symbols:home`) is the FILLED face, which is a visibly different
 * drawing. The two exceptions are the chevrons, which the set ships in one face.
 *
 * Regenerate after adding a screen that uses a new glyph.
 */
import type { Component } from "vue";

import IAccountTree from "~icons/material-symbols/account-tree-outline";
import IAddCircle from "~icons/material-symbols/add-circle-outline";
import IAddLink from "~icons/material-symbols/add-link-outline";
import IAddToQueue from "~icons/material-symbols/add-to-queue-outline";
import IAdminPanelSettings from "~icons/material-symbols/admin-panel-settings-outline";
import IAlternateEmail from "~icons/material-symbols/alternate-email-outline";
import IAnalytics from "~icons/material-symbols/analytics-outline";
import IApi from "~icons/material-symbols/api-outline";
import IApps from "~icons/material-symbols/apps-outline";
import IArrowBack from "~icons/material-symbols/arrow-back-outline";
import IArrowDropDown from "~icons/material-symbols/arrow-drop-down-outline";
import IArrowForward from "~icons/material-symbols/arrow-forward-outline";
import IArrowRight from "~icons/material-symbols/arrow-right-outline";
import IArrowUpward from "~icons/material-symbols/arrow-upward-outline";
import IAutoAwesome from "~icons/material-symbols/auto-awesome-outline";
import IAutorenew from "~icons/material-symbols/autorenew-outline";
import IBackup from "~icons/material-symbols/backup-outline";
import IBarChart from "~icons/material-symbols/bar-chart-outline";
import IBedtime from "~icons/material-symbols/bedtime-outline";
import IBlock from "~icons/material-symbols/block-outline";
import IBolt from "~icons/material-symbols/bolt-outline";
import IBugReport from "~icons/material-symbols/bug-report-outline";
import IBuild from "~icons/material-symbols/build-outline";
import ICalculate from "~icons/material-symbols/calculate-outline";
import ICallSplit from "~icons/material-symbols/call-split-outline";
import ICardMembership from "~icons/material-symbols/card-membership-outline";
import ICheck from "~icons/material-symbols/check-outline";
import ICheckBox from "~icons/material-symbols/check-box-outline";
import ICheckBoxOutlineBlank from "~icons/material-symbols/check-box-outline-blank-outline";
import ICheckCircle from "~icons/material-symbols/check-circle-outline";
import IChevronRight from "~icons/material-symbols/chevron-right-outline";
import IChips from "~icons/material-symbols/chips-outline";
import ICircle from "~icons/material-symbols/circle-outline";
import ICleaningServices from "~icons/material-symbols/cleaning-services-outline";
import IClose from "~icons/material-symbols/close-outline";
import ICloud from "~icons/material-symbols/cloud-outline";
import ICloudOff from "~icons/material-symbols/cloud-off-outline";
import ICloudSync from "~icons/material-symbols/cloud-sync-outline";
import ICloudUpload from "~icons/material-symbols/cloud-upload-outline";
import ICode from "~icons/material-symbols/code-outline";
import ICommit from "~icons/material-symbols/commit-outline";
import IConstruction from "~icons/material-symbols/construction-outline";
import IContentCopy from "~icons/material-symbols/content-copy-outline";
import ICreateNewFolder from "~icons/material-symbols/create-new-folder-outline";
import IDashboard from "~icons/material-symbols/dashboard-outline";
import IDatabase from "~icons/material-symbols/database-outline";
import IDelete from "~icons/material-symbols/delete-outline";
import IDeployedCode from "~icons/material-symbols/deployed-code-outline";
import IDescription from "~icons/material-symbols/description-outline";
import IDesktopWindows from "~icons/material-symbols/desktop-windows-outline";
import IDeveloperBoard from "~icons/material-symbols/developer-board-outline";
import IDns from "~icons/material-symbols/dns-outline";
import IDocs from "~icons/material-symbols/docs-outline";
import IDownload from "~icons/material-symbols/download-outline";
import IDraft from "~icons/material-symbols/draft-outline";
import IDriveFileMove from "~icons/material-symbols/drive-file-move-outline";
import IDriveFileRenameOutline from "~icons/material-symbols/drive-file-rename-outline-outline";
import IEnhancedEncryption from "~icons/material-symbols/enhanced-encryption-outline";
import IError from "~icons/material-symbols/error-outline";
import IExpandLess from "~icons/material-symbols/expand-less";
import IExpandMore from "~icons/material-symbols/expand-more";
import IExtension from "~icons/material-symbols/extension-outline";
import IFolder from "~icons/material-symbols/folder-outline";
import IFolderOpen from "~icons/material-symbols/folder-open-outline";
import IFolderZip from "~icons/material-symbols/folder-zip-outline";
import IGppBad from "~icons/material-symbols/gpp-bad-outline";
import IGppMaybe from "~icons/material-symbols/gpp-maybe-outline";
import IGridView from "~icons/material-symbols/grid-view-outline";
import IGroup from "~icons/material-symbols/group-outline";
import IHelp from "~icons/material-symbols/help-outline";
import IHistory from "~icons/material-symbols/history-outline";
import IHome from "~icons/material-symbols/home-outline";
import IImage from "~icons/material-symbols/image-outline";
import IInfo from "~icons/material-symbols/info-outline";
import IInventory2 from "~icons/material-symbols/inventory-2-outline";
import IJavascript from "~icons/material-symbols/javascript-outline";
import IKey from "~icons/material-symbols/key-outline";
import ILan from "~icons/material-symbols/lan-outline";
import ILanguage from "~icons/material-symbols/language-outline";
import ILinkOff from "~icons/material-symbols/link-off-outline";
import IList from "~icons/material-symbols/list-outline";
import ILocalFireDepartment from "~icons/material-symbols/local-fire-department-outline";
import ILocalParking from "~icons/material-symbols/local-parking-outline";
import ILock from "~icons/material-symbols/lock-outline";
import ILockClock from "~icons/material-symbols/lock-clock-outline";
import ILockOpen from "~icons/material-symbols/lock-open-outline";
import ILogin from "~icons/material-symbols/login-outline";
import ILogout from "~icons/material-symbols/logout-outline";
import IMail from "~icons/material-symbols/mail-outline";
import IMemory from "~icons/material-symbols/memory-outline";
import IMonitorHeart from "~icons/material-symbols/monitor-heart-outline";
import IMonitoring from "~icons/material-symbols/monitoring-outline";
import IMoreHoriz from "~icons/material-symbols/more-horiz-outline";
import IMoreVert from "~icons/material-symbols/more-vert-outline";
import IMove from "~icons/material-symbols/move-outline";
import INoteAdd from "~icons/material-symbols/note-add-outline";
import INotifications from "~icons/material-symbols/notifications-outline";
import INotificationsActive from "~icons/material-symbols/notifications-active-outline";
import IOpenInNew from "~icons/material-symbols/open-in-new-outline";
import IOverview from "~icons/material-symbols/overview-outline";
import IPerson from "~icons/material-symbols/person-outline";
import IPhonelinkLock from "~icons/material-symbols/phonelink-lock-outline";
import IPhp from "~icons/material-symbols/php-outline";
import IPlayCircle from "~icons/material-symbols/play-circle-outline";
import IPolicy from "~icons/material-symbols/policy-outline";
import IProgressActivity from "~icons/material-symbols/progress-activity-outline";
import IPublic from "~icons/material-symbols/public-outline";
import IReceiptLong from "~icons/material-symbols/receipt-long-outline";
import IRestartAlt from "~icons/material-symbols/restart-alt-outline";
import IRestore from "~icons/material-symbols/history-outline";
import ISchedule from "~icons/material-symbols/schedule-outline";
import IScheduleSend from "~icons/material-symbols/schedule-send-outline";
import ISearch from "~icons/material-symbols/search-outline";
import ISearchOff from "~icons/material-symbols/search-off-outline";
import ISecurity from "~icons/material-symbols/security-outline";
import ISensors from "~icons/material-symbols/sensors-outline";
import ISettings from "~icons/material-symbols/settings-outline";
import ISettingsEthernet from "~icons/material-symbols/settings-ethernet-outline";
import IShield from "~icons/material-symbols/shield-outline";
import IShieldLock from "~icons/material-symbols/shield-lock-outline";
import ISmartToy from "~icons/material-symbols/smart-toy-outline";
import ISoap from "~icons/material-symbols/soap-outline";
import ISpaceDashboard from "~icons/material-symbols/space-dashboard-outline";
import ISpeed from "~icons/material-symbols/speed-outline";
import IStacks from "~icons/material-symbols/stacks-outline";
import IStorage from "~icons/material-symbols/storage-outline";
import IStream from "~icons/material-symbols/stream-outline";
import ISwapHoriz from "~icons/material-symbols/swap-horiz-outline";
import ISwapVert from "~icons/material-symbols/swap-vert-outline";
import ISyncAlt from "~icons/material-symbols/sync-alt-outline";
import ISyncProblem from "~icons/material-symbols/sync-problem-outline";
import ISystemUpdateAlt from "~icons/material-symbols/system-update-alt-outline";
import ITableView from "~icons/material-symbols/table-view-outline";
import ITerminal from "~icons/material-symbols/terminal-outline";
import ITravelExplore from "~icons/material-symbols/travel-explore-outline";
import ITrendingUp from "~icons/material-symbols/trending-up-outline";
import ITune from "~icons/material-symbols/tune-outline";
import IUpdate from "~icons/material-symbols/update-outline";
import IUpload from "~icons/material-symbols/upload-outline";
import IUploadFile from "~icons/material-symbols/upload-file-outline";
import IVerified from "~icons/material-symbols/verified-outline";
import IVerifiedUser from "~icons/material-symbols/verified-user-outline";
import IViewTimeline from "~icons/material-symbols/view-timeline-outline";
import IVisibility from "~icons/material-symbols/visibility-outline";
import IVisibilityOff from "~icons/material-symbols/visibility-off-outline";
import IVpnKey from "~icons/material-symbols/vpn-key-outline";
import IWarning from "~icons/material-symbols/warning-outline";
import IWebhook from "~icons/material-symbols/webhook-outline";
import IWidgets from "~icons/material-symbols/widgets-outline";

export const ICONS: Readonly<Record<string, Component>> = {
  "account-tree": IAccountTree,
  "add-circle": IAddCircle,
  "add-link": IAddLink,
  "add-to-queue": IAddToQueue,
  "admin-panel-settings": IAdminPanelSettings,
  "alternate-email": IAlternateEmail,
  "analytics": IAnalytics,
  "api": IApi,
  "apps": IApps,
  "arrow-back": IArrowBack,
  "arrow-drop-down": IArrowDropDown,
  "arrow-forward": IArrowForward,
  "arrow-right": IArrowRight,
  "arrow-upward": IArrowUpward,
  "auto-awesome": IAutoAwesome,
  "autorenew": IAutorenew,
  "backup": IBackup,
  "bar-chart": IBarChart,
  "bedtime": IBedtime,
  "block": IBlock,
  "bolt": IBolt,
  "bug-report": IBugReport,
  "build": IBuild,
  "calculate": ICalculate,
  "call-split": ICallSplit,
  "card-membership": ICardMembership,
  "check": ICheck,
  "check-box": ICheckBox,
  "check-box-outline-blank": ICheckBoxOutlineBlank,
  "check-circle": ICheckCircle,
  "chevron-right": IChevronRight,
  "chips": IChips,
  "circle": ICircle,
  "cleaning-services": ICleaningServices,
  "close": IClose,
  "cloud": ICloud,
  "cloud-off": ICloudOff,
  "cloud-sync": ICloudSync,
  "cloud-upload": ICloudUpload,
  "code": ICode,
  "commit": ICommit,
  "construction": IConstruction,
  "content-copy": IContentCopy,
  "create-new-folder": ICreateNewFolder,
  "dashboard": IDashboard,
  "database": IDatabase,
  "delete": IDelete,
  "deployed-code": IDeployedCode,
  "description": IDescription,
  "desktop-windows": IDesktopWindows,
  "developer-board": IDeveloperBoard,
  "dns": IDns,
  "docs": IDocs,
  "download": IDownload,
  "draft": IDraft,
  "drive-file-move": IDriveFileMove,
  "drive-file-rename-outline": IDriveFileRenameOutline,
  "enhanced-encryption": IEnhancedEncryption,
  "error": IError,
  "expand-less": IExpandLess,
  "expand-more": IExpandMore,
  "extension": IExtension,
  "folder": IFolder,
  "folder-open": IFolderOpen,
  "folder-zip": IFolderZip,
  "gpp-bad": IGppBad,
  "gpp-maybe": IGppMaybe,
  "grid-view": IGridView,
  "group": IGroup,
  "help": IHelp,
  "history": IHistory,
  "home": IHome,
  "image": IImage,
  "info": IInfo,
  "inventory-2": IInventory2,
  "javascript": IJavascript,
  "key": IKey,
  "lan": ILan,
  "language": ILanguage,
  "link-off": ILinkOff,
  "list": IList,
  "local-fire-department": ILocalFireDepartment,
  "local-parking": ILocalParking,
  "lock": ILock,
  "lock-clock": ILockClock,
  "lock-open": ILockOpen,
  "login": ILogin,
  "logout": ILogout,
  "mail": IMail,
  "memory": IMemory,
  "monitor-heart": IMonitorHeart,
  "monitoring": IMonitoring,
  "more-horiz": IMoreHoriz,
  "more-vert": IMoreVert,
  "move": IMove,
  "note-add": INoteAdd,
  "notifications": INotifications,
  "notifications-active": INotificationsActive,
  "open-in-new": IOpenInNew,
  "overview": IOverview,
  "person": IPerson,
  "phonelink-lock": IPhonelinkLock,
  "php": IPhp,
  "play-circle": IPlayCircle,
  "policy": IPolicy,
  "progress-activity": IProgressActivity,
  "public": IPublic,
  "receipt-long": IReceiptLong,
  "restart-alt": IRestartAlt,
  "restore": IRestore,
  "schedule": ISchedule,
  "schedule-send": IScheduleSend,
  "search": ISearch,
  "search-off": ISearchOff,
  "security": ISecurity,
  "sensors": ISensors,
  "settings": ISettings,
  "settings-ethernet": ISettingsEthernet,
  "shield": IShield,
  "shield-lock": IShieldLock,
  "smart-toy": ISmartToy,
  "soap": ISoap,
  "space-dashboard": ISpaceDashboard,
  "speed": ISpeed,
  "stacks": IStacks,
  "storage": IStorage,
  "stream": IStream,
  "swap-horiz": ISwapHoriz,
  "swap-vert": ISwapVert,
  "sync-alt": ISyncAlt,
  "sync-problem": ISyncProblem,
  "system-update-alt": ISystemUpdateAlt,
  "table-view": ITableView,
  "terminal": ITerminal,
  "travel-explore": ITravelExplore,
  "trending-up": ITrendingUp,
  "tune": ITune,
  "update": IUpdate,
  "upload": IUpload,
  "upload-file": IUploadFile,
  "verified": IVerified,
  "verified-user": IVerifiedUser,
  "view-timeline": IViewTimeline,
  "visibility": IVisibility,
  "visibility-off": IVisibilityOff,
  "vpn-key": IVpnKey,
  "warning": IWarning,
  "webhook": IWebhook,
  "widgets": IWidgets,
};

export type IconName = keyof typeof ICONS;

/** Whether a name will render. Lets a caller fall back instead of rendering nothing. */
export function hasIcon(name: string): boolean {
  return name in ICONS;
}
