package httpapi

import (
	"context"
	"encoding/json"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/thisisnkp/heropanel/internal/apps"
	"github.com/thisisnkp/heropanel/internal/audit"
	"github.com/thisisnkp/heropanel/internal/auth"
	brokerclient "github.com/thisisnkp/heropanel/internal/broker"
	"github.com/thisisnkp/heropanel/internal/config"
	"github.com/thisisnkp/heropanel/internal/database"
	"github.com/thisisnkp/heropanel/internal/dns"
	"github.com/thisisnkp/heropanel/internal/docker"
	"github.com/thisisnkp/heropanel/internal/domain"
	"github.com/thisisnkp/heropanel/internal/files"
	"github.com/thisisnkp/heropanel/internal/git"
	"github.com/thisisnkp/heropanel/internal/job"
	"github.com/thisisnkp/heropanel/internal/php"
	"github.com/thisisnkp/heropanel/internal/registry"
	"github.com/thisisnkp/heropanel/internal/runtime"
	"github.com/thisisnkp/heropanel/internal/site"
	"github.com/thisisnkp/heropanel/internal/ssl"
	"github.com/thisisnkp/heropanel/internal/terminal"
	"github.com/thisisnkp/heropanel/internal/ws"
)

// stubUsers satisfies UserDirectory so the /users route mounts. It is never
// invoked — the spec builder only walks the routing tree, it does not serve.
type stubUsers struct{}

func (stubUsers) List(context.Context, int, int) ([]UserSummary, error) { return nil, nil }

// The File Manager and the terminal are the two services a zero-value pointer
// cannot stand in for: files.Service and terminal.Service keep their
// dependencies unexported, and the terminal route additionally mounts only when
// Available() reports a broker. Without real constructors here their entire
// route group silently vanished from the walk — and therefore from the
// published OpenAPI spec — which is exactly the kind of gap the drift test is
// supposed to catch and could not, because it only checks the routes it can see.
type stubFileSites struct{}

func (stubFileSites) Resolve(context.Context, string) (*files.SiteRef, error) { return nil, nil }

type stubFileBroker struct{}

func (stubFileBroker) Invoke(context.Context, string, any) (map[string]any, error) { return nil, nil }

// stubDockerBroker reports a daemon that is present, so the Docker routes mount
// and appear in the generated spec. The service refuses every operation when no
// daemon answers, which would take its whole route group out of the walk.
type stubDockerBroker struct{}

func (stubDockerBroker) Invoke(_ context.Context, capability string, _ any) (map[string]any, error) {
	if capability == "docker.info" {
		return map[string]any{"available": true}, nil
	}
	return map[string]any{}, nil
}

type stubTerminalSites struct{}

func (stubTerminalSites) Resolve(context.Context, string) (*terminal.SiteRef, error) {
	return nil, nil
}

type stubStreamGateway struct{}

func (stubStreamGateway) OpenStream(context.Context, string, any) (brokerclient.Stream, error) {
	return nil, nil
}

// stubHealth stands in for the datastore/Redis/broker health probes.
type stubHealth struct{}

func (stubHealth) Health(context.Context) error { return nil }

// stubRecordings is the recordings metadata store the router needs to mount the
// recording routes.
type stubRecordings struct{}

func (stubRecordings) Create(context.Context, *terminal.Recording) error { return nil }
func (stubRecordings) Finish(context.Context, string, int64, int64, bool) error {
	return nil
}
func (stubRecordings) Get(context.Context, string) (*terminal.Recording, error) {
	return &terminal.Recording{}, nil
}
func (stubRecordings) List(context.Context, int64, int, int) ([]terminal.Recording, error) {
	return nil, nil
}
func (stubRecordings) Delete(context.Context, string) (string, error) { return "", nil }
func (stubRecordings) Expired(context.Context, time.Time, int) ([]terminal.Recording, error) {
	return nil, nil
}

// TestFullRouterMountsEveryService is the guard for the failure that let the
// whole File Manager and terminal API vanish from docs/openapi.json.
//
// The spec is generated by *walking a router*. Optional services mount their
// routes behind an `if d.X != nil` check, so any service fullRouter forgets is
// simply absent from the walk — and the golden test then happily compares one
// incomplete spec against another and passes. The published API lost about 1500
// lines that way, silently, for a whole phase.
//
// Reflection is the point: a hand-written list here would need the same manual
// update that was missed in the first place. Adding a field to Deps and not to
// fullRouter now fails immediately, naming the field.
func TestFullRouterMountsEveryService(t *testing.T) {
	// Rebuild the Deps fullRouter passes, so the check sees exactly what it sets.
	// (fullRouter returns the router, not its inputs, so this mirrors the literal;
	// the assertion below is what keeps the two honest.)
	deps := fullRouterDeps(t)

	v := reflect.ValueOf(deps)
	for i := 0; i < v.NumField(); i++ {
		field := v.Type().Field(i)
		switch v.Field(i).Kind() {
		case reflect.Ptr, reflect.Interface, reflect.Map, reflect.Slice, reflect.Func:
			if v.Field(i).IsNil() {
				t.Errorf("fullRouter leaves Deps.%s nil — any routes it gates are missing from the walk, "+
					"and therefore from docs/openapi.json, with no other test noticing", field.Name)
			}
		}
	}
}

// fullRouterDeps is every service the router knows about, all non-nil.
//
// Most are zero-value pointers: router construction captures them in handler
// closures but never dereferences them, so that is safe for a walk. Files and
// Terminal need real constructors — their dependencies are unexported, and the
// terminal route mounts only when Available() reports a broker. Auth is the gate
// for the whole authenticated group, so it must be present too.
//
// It is a separate function from fullRouter so TestFullRouterMountsEveryService
// can inspect the same value the router is built from.
func fullRouterDeps(t *testing.T) Deps {
	t.Helper()
	cfg := config.Default()
	cfg.Security.RateLimit.Enabled = false
	dockerStub := docker.New(stubDockerBroker{}).WithStreams(stubStreamGateway{})
	return Deps{
		Ctx:       context.Background(),
		Config:    cfg,
		Logger:    slog.New(slog.NewTextHandler(io.Discard, nil)),
		Version:   "test",
		StartedAt: time.Now(),
		Auth:      &auth.Service{},
		Audit:     &audit.Service{},
		Users:     stubUsers{},
		Sites:     &site.Service{},
		PHP:       &php.Service{},
		Databases: &database.Service{},
		SSL:       &ssl.Service{},
		DNS:       &dns.Service{},
		Domains:   &domain.Service{},
		Git:       &git.Service{},
		Runtime:   &runtime.Service{},
		Jobs:      &job.Dispatcher{},
		Registry:  registry.New(),
		// Apps rides on Docker, so both use the same daemon-present stub — and the
		// Apps route group only mounts when Apps is non-nil, so it must be here or
		// the whole one-click API vanishes from the walked spec.
		Docker:   dockerStub,
		Apps:     apps.New(dockerStub),
		Files:    files.NewService(stubFileSites{}, stubFileBroker{}),
		Terminal: terminal.NewService(stubTerminalSites{}, stubStreamGateway{}),
		Recordings: terminal.NewRecordingStore(
			t.TempDir(), stubRecordings{}, terminal.DefaultRetention),
		WS:     &ws.Hub{},
		DB:     stubHealth{},
		Redis:  stubHealth{},
		Broker: stubHealth{},
	}
}

// fullRouter builds the router every spec test walks.
func fullRouter(t *testing.T) chi.Routes {
	t.Helper()
	h := NewRouter(fullRouterDeps(t))
	routes, ok := h.(chi.Routes)
	if !ok {
		t.Fatalf("router is not chi.Routes (%T)", h)
	}
	return routes
}

// TestOpenAPINoUndocumentedRoutes is the drift guard: every route actually
// mounted must have an apiDocs entry. When this fails, the fix is to document
// the new route, not to loosen the test — that is the whole point.
func TestOpenAPINoUndocumentedRoutes(t *testing.T) {
	buildOpenAPI(fullRouter(t), "test")
	if undoc := UndocumentedRoutes(); len(undoc) > 0 {
		t.Fatalf("routes are mounted but undocumented (add them to apiDocs):\n  %s",
			strings.Join(undoc, "\n  "))
	}
}

// TestOpenAPIRefsResolve ensures no operation or schema references a component
// schema that does not exist — a dangling $ref makes the document unusable to
// generators.
func TestOpenAPIRefsResolve(t *testing.T) {
	doc := buildOpenAPI(fullRouter(t), "test")
	var refs []string
	collectRefs(doc, &refs)
	if len(refs) == 0 {
		t.Fatal("expected the document to contain $refs")
	}
	for _, r := range refs {
		name := strings.TrimPrefix(r, "#/components/schemas/")
		if name == r {
			t.Errorf("unexpected $ref form: %q", r)
			continue
		}
		if _, ok := openapiSchemas[name]; !ok {
			t.Errorf("$ref %q points at an undefined schema", r)
		}
	}
}

// TestOpenAPIShape checks the top-level document is a well-formed OpenAPI 3.1
// object with the pieces tooling requires.
func TestOpenAPIShape(t *testing.T) {
	doc := buildOpenAPI(fullRouter(t), "test")
	if doc["openapi"] != "3.1.0" {
		t.Errorf("openapi = %v, want 3.1.0", doc["openapi"])
	}
	paths, _ := doc["paths"].(map[string]any)
	if len(paths) < 50 {
		t.Errorf("expected the full surface (50+ paths), got %d", len(paths))
	}
	// Spot-check that a permission-gated operation surfaces its scope and that
	// path params are derived.
	sites, _ := paths["/api/v1/sites/{uid}"].(map[string]any)
	get, _ := sites["get"].(map[string]any)
	if get["x-required-permission"] != "site.read" {
		t.Errorf("GET /sites/{uid} permission = %v, want site.read", get["x-required-permission"])
	}
	params, _ := get["parameters"].([]any)
	if len(params) != 1 {
		t.Fatalf("expected 1 path param on /sites/{uid}, got %d", len(params))
	}
	comps, _ := doc["components"].(map[string]any)
	schemes, _ := comps["securitySchemes"].(map[string]any)
	if _, ok := schemes["sessionCookie"]; !ok {
		t.Error("missing sessionCookie security scheme")
	}
	if _, ok := schemes["apiKey"]; !ok {
		t.Error("missing apiKey security scheme")
	}
}

// TestOpenAPIGolden keeps docs/openapi.json in step with the code. Regenerate
// with:  HP_UPDATE_OPENAPI=1 go test ./internal/httpapi -run Golden
func TestOpenAPIGolden(t *testing.T) {
	doc := buildOpenAPI(fullRouter(t), openapiGoldenVersion)
	got, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	got = append(got, '\n')

	path := filepath.Join("..", "..", "docs", "openapi.json")
	if os.Getenv("HP_UPDATE_OPENAPI") == "1" {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", path)
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (regenerate with HP_UPDATE_OPENAPI=1): %v", err)
	}
	if strings.ReplaceAll(string(want), "\r\n", "\n") != string(got) {
		t.Fatalf("docs/openapi.json is stale — regenerate with HP_UPDATE_OPENAPI=1 go test ./internal/httpapi -run Golden")
	}
}

// openapiGoldenVersion pins the version string in the committed spec so the
// golden does not churn on every build's version stamp.
const openapiGoldenVersion = "v1"

func collectRefs(v any, out *[]string) {
	switch t := v.(type) {
	case map[string]any:
		for k, val := range t {
			if k == "$ref" {
				if s, ok := val.(string); ok {
					*out = append(*out, s)
				}
				continue
			}
			collectRefs(val, out)
		}
	case []any:
		for _, e := range t {
			collectRefs(e, out)
		}
	}
}
