/**
 * Regenerates src/components/ui/icons.ts.
 *
 * Two things this script exists to get right, both of which were wrong when the
 * registry was written by hand:
 *
 * 1. The design renders Material Symbols with `FILL 0` — the *outlined* face.
 *    Iconify's `material-symbols:home` is the FILLED glyph; the outlined one is
 *    `material-symbols:home-outline`. Importing the bare name gave every icon in
 *    the panel a solid body the design never draws. Each name here resolves to
 *    its `-outline` variant when the set has one, and only falls back to the
 *    bare name when it does not (the chevrons, which are strokes either way).
 *
 * 2. Names are collected from the source rather than maintained by hand, so a
 *    screen that uses a new glyph cannot ship with a name the registry lacks —
 *    that renders nothing at all and still looks deliberate.
 *
 *   node scripts/gen-icons.mjs
 */
import { createRequire } from "node:module";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const require = createRequire(import.meta.url);
const SET = require("@iconify-json/material-symbols/icons.json");
const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const SRC = join(ROOT, "src");
const OUT = join(SRC, "components/ui/icons.ts");

const exists = (n) => n in SET.icons || (SET.aliases && n in SET.aliases);

/** Names the design uses that this icon set does not carry under that name. */
const ALIASES = {
  // Material Symbols draws `https` as the same padlock as `lock`; Iconify only
  // ships the one name.
  https: "lock",
  // `gpp_good` was folded into `verified_user` upstream — same shield-with-tick.
  "gpp-good": "verified-user",
  // `restore` and `history` are the same clock-with-reverse-arrow drawing.
  restore: "history",
  // `notifications_none` is precisely the outlined bell.
  "notifications-none": "notifications",
};

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (/\.(ts|vue)$/.test(p) && !p.endsWith(".test.ts")) out.push(p);
  }
  return out;
}

const files = walk(SRC).filter((f) => f !== OUT);
const found = new Map(); // name -> Set of files that ask for it

// Every place a glyph name is written: an `icon:` field in a data module, a
// `name="..."` / `:name="cond ? 'a' : 'b'"` on <NxIcon>, or an `icon="..."`
// prop passed to a component that forwards it.
const PATTERNS = [
  /\bicons?:\s*"([a-z0-9-]+)"/g,
  /\bicons?:\s*'([a-z0-9-]+)'/g,
  /\bicon="([a-z0-9-]+)"/g,
  /\bname="([a-z0-9-]+)"\s*(?=[^>]*\/?>)/g,
  /:name="[^"]*?'([a-z0-9-]+)'/g,
  /:name="[^"]*?'[a-z0-9-]+'\s*:\s*'([a-z0-9-]+)'/g,
  /:icon="[^"]*?'([a-z0-9-]+)'/g,
  /\bstatusIcon:\s*"([a-z0-9-]+)"/g,
  /\bapp\(\s*"[^"]*",\s*"([a-z0-9-]+)"/g,
];

for (const f of files) {
  const text = readFileSync(f, "utf8");
  for (const re of PATTERNS) {
    for (const m of text.matchAll(re)) {
      const raw = m[1];
      if (!raw || raw.length < 3) continue;
      if (!exists(raw) && !exists(raw + "-outline") && !(raw in ALIASES)) continue;
      if (!found.has(raw)) found.set(raw, new Set());
      found.get(raw).add(relative(SRC, f).split(sep).join("/"));
    }
  }
}

// Names the registry already carried stay in it: dropping one silently would
// blank an icon somewhere the patterns above did not reach.
for (const m of readFileSync(OUT, "utf8").matchAll(/^  "([a-z0-9-]+)":/gm)) {
  if (!found.has(m[1])) found.set(m[1], new Set(["(kept from previous registry)"]));
}

const names = [...found.keys()].sort();
const pascal = (n) => "I" + n.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const resolved = names.map((n) => {
  const base = ALIASES[n] ?? n;
  const target = exists(base + "-outline") ? base + "-outline" : base;
  if (!exists(target)) throw new Error(`no glyph for ${n} (tried ${target})`);
  return { name: n, target, ident: pascal(n) };
});

const header = `/**
 * The icon registry — generated by scripts/gen-icons.mjs, do not edit by hand.
 *
 * unplugin-icons resolves each import at build time and inlines the SVG, so a
 * screen ships only the glyphs it renders. That resolution is static, which is
 * why this file exists: the navigation model stores icon *names* as strings, and
 * a string cannot be an import. Mapping them here keeps the dynamic lookup
 * without falling back to Iconify's runtime API, which would fetch every glyph
 * over the network on first paint.
 *
 * Every name resolves to the \`-outline\` variant of the glyph. The design sets
 * \`FILL 0\` on Material Symbols, so its icons are outlined; Iconify's bare name
 * (\`material-symbols:home\`) is the FILLED face, which is a visibly different
 * drawing. The two exceptions are the chevrons, which the set ships in one face.
 *
 * Regenerate after adding a screen that uses a new glyph.
 */
import type { Component } from "vue";

`;

const imports = resolved.map((r) => `import ${r.ident} from "~icons/material-symbols/${r.target}";`).join("\n");
const body = resolved.map((r) => `  "${r.name}": ${r.ident},`).join("\n");

const footer = `

export const ICONS: Readonly<Record<string, Component>> = {
${body}
};

export type IconName = keyof typeof ICONS;

/** Whether a name will render. Lets a caller fall back instead of rendering nothing. */
export function hasIcon(name: string): boolean {
  return name in ICONS;
}
`;

writeFileSync(OUT, header + imports + footer, "utf8");

const filled = resolved.filter((r) => !r.target.endsWith("-outline"));
console.log(`wrote ${resolved.length} icons -> ${relative(ROOT, OUT)}`);
console.log(`outlined: ${resolved.length - filled.length}, no outline face: ${filled.map((f) => f.name).join(", ")}`);
