package capabilities

import "github.com/thisisnkp/heropanel/broker/capability"

// All returns every built-in capability. The broker registers these at startup.
// New privileged operations are added here (and gated by policy).
func All() []capability.Capability {
	return []capability.Capability{
		ServiceRestart{},
		SystemUserCreate{},
		SystemUserDelete{},
		SiteCreateDirs{},
		SiteRemoveDirs{},
		SiteApplySlice{},
		SiteRemoveSlice{},
		SiteReadLog{},
		SiteCopyTree{},
		FileList{},
		FileRead{},
		FileWrite{},
		FileMkdir{},
		FileRemove{},
		FileRename{},
		FileCopy{},
		FileChmod{},
		FileExtract{},
		FileCompress{},
		FileChown{},
		FileSearch{},
		WebServerApply{},
		PHPWritePool{},
		PHPListExtensions{},
		PHPSetExtension{},
		DBCreate{},
		DBDrop{},
		DBUserCreate{},
		DBUserDrop{},
		DBGrant{},
		DBRevoke{},
		DBSize{},
		DBExport{},
		DBImport{},
		CertInstall{},
		CertWriteChallenge{},
		GitDeploy{},
		GitRollback{},
		AppUnitApply{},
		AppUnitControl{},
		AppUnitRemove{},
		DNSWriteZone{},
		DNSRemoveZone{},
		DockerInfo{},
		ContainerList{},
		ContainerInspect{},
		ContainerLogs{},
		ContainerStats{},
		ContainerStart{},
		ContainerStop{},
		ContainerRestart{},
		ContainerRemove{},
		ImageList{},
		ImagePull{},
		ImageRemove{},
		ImagePrune{},
		ContainerCreate{},
		VolumeList{},
		VolumeCreate{},
		VolumeRemove{},
		VolumeInspect{},
		NetworkList{},
		NetworkCreate{},
		NetworkRemove{},
		NetworkInspect{},
		ComposeUp{},
		ComposeDown{},
		ComposePs{},
		ComposeLogs{},
	}
}
