package capabilities

import (
	"encoding/json"
	"strings"
	"time"

	"github.com/thisisnkp/nexpanel/broker/capability"
	"github.com/thisisnkp/nexpanel/broker/exec"
	"github.com/thisisnkp/nexpanel/pkg/errx"
)

// Host firewall via nftables, with a snapshot-and-revert safety net.
//
// The danger a firewall carries is unique: a wrong rule can lock the operator
// out of the very box they are configuring, with no way back in. So an apply is
// two-phase — it snapshots the live ruleset first, applies the new one, and
// leaves the snapshot as a *pending* file. If the change is confirmed, the
// snapshot is discarded; if it is not, the security module reverts to it. The
// broker owns only the three privileged verbs (snapshot+apply, discard,
// restore); the timer that decides "not confirmed" lives in unprivileged npd.

const (
	nftPath = "/usr/sbin/nft"
	// firewallDir holds the root-only snapshot; its existence means a pending,
	// unconfirmed apply that the security module's guard will revert.
	firewallDir      = "/var/lib/nexpanel/firewall"
	firewallSnapshot = firewallDir + "/rollback.nft"
	firewallDesired  = firewallDir + "/desired.nft"
)

// maxRuleset bounds a rendered ruleset. It is generated by npd from validated
// rows; a quarter-megabyte is thousands of rules — anything larger is a bug.
const maxRuleset = 256 << 10

// ── firewall.apply ───────────────────────────────────────────────────────────

// FirewallApply snapshots the live ruleset, applies the rendered one, and
// leaves the snapshot pending. It refuses when a snapshot is already pending —
// an operator must confirm or revert the last change before stacking another,
// so the pending snapshot always holds the true pre-change baseline.
type FirewallApply struct{}

type firewallApplyInput struct {
	Ruleset string `json:"ruleset"`
}

// Name implements capability.Capability.
func (FirewallApply) Name() string { return "firewall.apply" }

// Execute implements capability.Capability.
func (FirewallApply) Execute(c capability.Context, raw json.RawMessage) (capability.Result, error) {
	var in firewallApplyInput
	if err := json.Unmarshal(raw, &in); err != nil {
		return capability.Result{}, errx.Validation("bad_input", "Invalid input for firewall.apply.")
	}
	if len(in.Ruleset) == 0 || len(in.Ruleset) > maxRuleset || strings.ContainsRune(in.Ruleset, 0) {
		return capability.Result{}, errx.Validation("bad_ruleset", "The rendered ruleset is invalid.")
	}
	if err := ensureFirewallDir(c); err != nil {
		return capability.Result{}, err
	}
	if ok, _ := c.FS.Exists(firewallSnapshot); ok {
		return capability.Result{}, errx.New(errx.KindConflict, "apply_pending",
			"A firewall change is already awaiting confirmation; confirm or revert it first.")
	}

	// Snapshot the live ruleset BEFORE touching anything. `nft list ruleset`
	// prints a reloadable form; a leading `flush ruleset` makes restoring it a
	// full replacement rather than an append.
	snap, err := c.Runner.Run(c.Ctx, exec.Command{
		Path: nftPath, Args: []string{"list", "ruleset"}, Timeout: 30 * time.Second,
	})
	if err != nil || snap.ExitCode != 0 {
		return capability.Result{}, errx.New(errx.KindUpstream, "snapshot_failed",
			"Could not read the current firewall ruleset.")
	}
	if err := c.FS.WriteFile(firewallSnapshot, []byte("flush ruleset\n"+string(snap.Stdout)), 0o600); err != nil {
		return capability.Result{}, errx.Upstream(err, "snapshot_failed", "Could not save the firewall snapshot.")
	}

	// Apply the new ruleset. `nft -f` is atomic: a bad ruleset changes nothing,
	// so on failure we simply drop the snapshot — the box is exactly as it was.
	if err := c.FS.WriteFile(firewallDesired, []byte(in.Ruleset), 0o600); err != nil {
		_ = c.FS.Remove(firewallSnapshot)
		return capability.Result{}, errx.Upstream(err, "apply_failed", "Could not stage the firewall ruleset.")
	}
	res, err := c.Runner.Run(c.Ctx, exec.Command{
		Path: nftPath, Args: []string{"-f", firewallDesired}, Timeout: 30 * time.Second,
	})
	if err != nil || res.ExitCode != 0 {
		_ = c.FS.Remove(firewallSnapshot)
		return capability.Result{}, errx.New(errx.KindUpstream, "apply_failed",
			"The firewall ruleset was rejected by nft: "+logTail(res, 500))
	}
	return capability.Result{Data: map[string]any{"applied": true, "pending": true}}, nil
}

// ── firewall.confirm ─────────────────────────────────────────────────────────

// FirewallConfirm discards the pending snapshot, making the last apply
// permanent. Idempotent: no pending snapshot is success (already confirmed).
type FirewallConfirm struct{}

// Name implements capability.Capability.
func (FirewallConfirm) Name() string { return "firewall.confirm" }

// Execute implements capability.Capability.
func (FirewallConfirm) Execute(c capability.Context, _ json.RawMessage) (capability.Result, error) {
	if ok, _ := c.FS.Exists(firewallSnapshot); !ok {
		return capability.Result{Data: map[string]any{"confirmed": true, "was_pending": false}}, nil
	}
	if err := c.FS.Remove(firewallSnapshot); err != nil {
		return capability.Result{}, errx.Upstream(err, "confirm_failed", "Could not confirm the firewall change.")
	}
	return capability.Result{Data: map[string]any{"confirmed": true, "was_pending": true}}, nil
}

// ── firewall.rollback ────────────────────────────────────────────────────────

// FirewallRollback restores the pending snapshot and discards it. This is what
// the security module's guard calls when a change goes unconfirmed — and what
// an operator who realises the mistake can call by hand. Idempotent.
type FirewallRollback struct{}

// Name implements capability.Capability.
func (FirewallRollback) Name() string { return "firewall.rollback" }

// Execute implements capability.Capability.
func (FirewallRollback) Execute(c capability.Context, _ json.RawMessage) (capability.Result, error) {
	if ok, _ := c.FS.Exists(firewallSnapshot); !ok {
		return capability.Result{Data: map[string]any{"rolled_back": false}}, nil
	}
	res, err := c.Runner.Run(c.Ctx, exec.Command{
		Path: nftPath, Args: []string{"-f", firewallSnapshot}, Timeout: 30 * time.Second,
	})
	if err != nil || res.ExitCode != 0 {
		return capability.Result{}, errx.New(errx.KindUpstream, "rollback_failed",
			"Could not restore the previous firewall ruleset.")
	}
	_ = c.FS.Remove(firewallSnapshot)
	return capability.Result{Data: map[string]any{"rolled_back": true}}, nil
}

// ── firewall.status ──────────────────────────────────────────────────────────

// FirewallStatus reports the live ruleset and whether a change is pending. A
// read verb — it runs `nft list ruleset` and looks for the snapshot file.
type FirewallStatus struct{}

// Name implements capability.Capability.
func (FirewallStatus) Name() string { return "firewall.status" }

// Execute implements capability.Capability.
func (FirewallStatus) Execute(c capability.Context, _ json.RawMessage) (capability.Result, error) {
	res, err := c.Runner.Run(c.Ctx, exec.Command{
		Path: nftPath, Args: []string{"list", "ruleset"}, Timeout: 30 * time.Second,
	})
	if err != nil {
		return capability.Result{}, errx.Upstream(err, "status_failed", "Could not read the firewall ruleset.")
	}
	pending, _ := c.FS.Exists(firewallSnapshot)
	live := string(res.Stdout)
	if len(live) > maxRuleset {
		live = live[:maxRuleset]
	}
	return capability.Result{Data: map[string]any{
		"ruleset": live, "pending": pending, "running": res.ExitCode == 0,
	}}, nil
}

// ensureFirewallDir creates the root-only snapshot directory (0700 root).
func ensureFirewallDir(c capability.Context) error {
	res, err := c.Runner.Run(c.Ctx, exec.Command{
		Path: installPath, Args: []string{"-d", "-m", "0700", firewallDir}, Timeout: 20 * time.Second,
	})
	if err != nil || res.ExitCode != 0 {
		return errx.New(errx.KindUpstream, "apply_failed", "Could not create the firewall state directory.")
	}
	return nil
}
