/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiPanel: typeof import('./components/ai/AiPanel.vue')['default']
    AppRail: typeof import('./components/nav/AppRail.vue')['default']
    AppSidebar: typeof import('./components/nav/AppSidebar.vue')['default']
    AppsSidebar: typeof import('./components/nav/AppsSidebar.vue')['default']
    AppTopbar: typeof import('./components/nav/AppTopbar.vue')['default']
    ContextNavRow: typeof import('./components/nav/ContextNavRow.vue')['default']
    ContextSidebar: typeof import('./components/nav/ContextSidebar.vue')['default']
    CreateSiteWizard: typeof import('./components/sites/CreateSiteWizard.vue')['default']
    DomainSidebar: typeof import('./components/nav/DomainSidebar.vue')['default']
    FileEditor: typeof import('./components/files/FileEditor.vue')['default']
    JobTray: typeof import('./components/ui/JobTray.vue')['default']
    MalwareEngines: typeof import('./components/security/MalwareEngines.vue')['default']
    MobileHeader: typeof import('./components/nav/MobileHeader.vue')['default']
    MobileNavSheet: typeof import('./components/nav/MobileNavSheet.vue')['default']
    MobileTabBar: typeof import('./components/nav/MobileTabBar.vue')['default']
    NxBadge: typeof import('./components/ui/NxBadge.vue')['default']
    NxButton: typeof import('./components/ui/NxButton.vue')['default']
    NxCallout: typeof import('./components/ui/NxCallout.vue')['default']
    NxCard: typeof import('./components/ui/NxCard.vue')['default']
    NxEmptyState: typeof import('./components/ui/NxEmptyState.vue')['default']
    NxField: typeof import('./components/ui/NxField.vue')['default']
    NxIcon: typeof import('./components/ui/NxIcon.vue')['default']
    NxInput: typeof import('./components/ui/NxInput.vue')['default']
    NxLogPanel: typeof import('./components/ui/NxLogPanel.vue')['default']
    NxMenu: typeof import('./components/ui/NxMenu.vue')['default']
    NxMeter: typeof import('./components/ui/NxMeter.vue')['default']
    NxModal: typeof import('./components/ui/NxModal.vue')['default']
    NxPageHeader: typeof import('./components/ui/NxPageHeader.vue')['default']
    NxSelect: typeof import('./components/ui/NxSelect.vue')['default']
    NxSkeleton: typeof import('./components/ui/NxSkeleton.vue')['default']
    NxSparkBars: typeof import('./components/ui/NxSparkBars.vue')['default']
    NxStat: typeof import('./components/ui/NxStat.vue')['default']
    NxSwitcher: typeof import('./components/ui/NxSwitcher.vue')['default']
    NxTable: typeof import('./components/ui/NxTable.vue')['default']
    NxTile: typeof import('./components/ui/NxTile.vue')['default']
    NxToggle: typeof import('./components/ui/NxToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPalette: typeof import('./components/ui/SearchPalette.vue')['default']
    SecuritySidebar: typeof import('./components/nav/SecuritySidebar.vue')['default']
    SiteDrawer: typeof import('./components/nav/SiteDrawer.vue')['default']
    SiteHeader: typeof import('./components/site/SiteHeader.vue')['default']
    SpecScreen: typeof import('./components/common/SpecScreen.vue')['default']
    ToastStack: typeof import('./components/ui/ToastStack.vue')['default']
  }
}
