/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppRail: typeof import('./components/nav/AppRail.vue')['default']
    AppSidebar: typeof import('./components/nav/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/nav/AppTopbar.vue')['default']
    MobileHeader: typeof import('./components/nav/MobileHeader.vue')['default']
    MobileNavSheet: typeof import('./components/nav/MobileNavSheet.vue')['default']
    MobileTabBar: typeof import('./components/nav/MobileTabBar.vue')['default']
    NxBadge: typeof import('./components/ui/NxBadge.vue')['default']
    NxButton: typeof import('./components/ui/NxButton.vue')['default']
    NxCard: typeof import('./components/ui/NxCard.vue')['default']
    NxEmptyState: typeof import('./components/ui/NxEmptyState.vue')['default']
    NxIcon: typeof import('./components/ui/NxIcon.vue')['default']
    NxLogPanel: typeof import('./components/ui/NxLogPanel.vue')['default']
    NxMeter: typeof import('./components/ui/NxMeter.vue')['default']
    NxPageHeader: typeof import('./components/ui/NxPageHeader.vue')['default']
    NxScreenPending: typeof import('./components/ui/NxScreenPending.vue')['default']
    NxSkeleton: typeof import('./components/ui/NxSkeleton.vue')['default']
    NxSparkBars: typeof import('./components/ui/NxSparkBars.vue')['default']
    NxStat: typeof import('./components/ui/NxStat.vue')['default']
    NxTable: typeof import('./components/ui/NxTable.vue')['default']
    NxTabs: typeof import('./components/ui/NxTabs.vue')['default']
    NxToggle: typeof import('./components/ui/NxToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteDrawer: typeof import('./components/nav/SiteDrawer.vue')['default']
    ToastStack: typeof import('./components/ui/ToastStack.vue')['default']
  }
}
